### ISSUE TITLE
Reduce severity of warning falling back to SENTRY_DSN environment variable

### ISSUE THREAD

**Issue by mikeclarke** [getsentry/sentry-airflow#10]
Related to #8, we should support `SENTRY_DSN` environment variables without logging a warning (since this is a normal way of configuring the Sentry integration).

**Comment by psdon** [comment]
This is not a warning, its's a bug. `SENTRY_DSN` does not get the value and assign it to `self.dsn`

**Comment by tiopi** [comment]
`SENTRY_DSN` environment variable gets set in https://github.com/getsentry/sentry-python/blob/master/sentry_sdk/client.py#L55. I have made the fix and changed it from a warning to a debug logging statement.
