### ISSUE TITLE
Ability to add environment to Config

### ISSUE THREAD

**Issue by sdzharkov** [getsentry/sentry-airflow#33]
Hey Sentry team,

I was able to configure the Airflow [1.10.6] and the Sentry integration, and push up errors to Sentry locally. Is there a way to specify which environment the errors should be sent to? I.e creating a development environment vs the prod environment all errors are currently being sent to.

**Comment by mikeclarke** [comment]
@sdzharkov by default you can set the `SENTRY_ENVIRONMENT` env variable (https://docs.sentry.io/error-reporting/configuration/?platform=python#environment). another option is the feature in #19, would that be useful for you? it would allow for per-connection configuration of the Sentry environment via the Airflow UI.

**Comment by sdzharkov** [comment]
Ah yes I completely forgot about environment variable config - that's exactly what I was looking for. #19 would also be useful for future configs. Thanks for the help @mikeclarke
