### ISSUE TITLE
Example usage

### ISSUE THREAD

**Issue by maxcountryman** [getsentry/sentry-airflow#6]
Thanks for putting together this plugin--I'm curious what the recommended approach for integrating this with our DAGs is. A simple example would be very much appreciated.

**Comment by tiopi** [comment]
It's great to hear that @maxcountryman! A simple example of how to use this plugin to handle Airflow wide exceptions would be to add `sentry_plugin/` folder into `$AIRFLOW_HOME/plugins` directory, and then setting your `SENTRY_DSN` in the environment variables. Then, Sentry will start catching exceptions that happen throughout Airflow. 

An example of an error that would be handled is:
```python
from airflow import DAG
from airflow.operators.bash_operator import BashOperator
from airflow.operators.python_operator import PythonOperator
from datetime import datetime, timedelta
from airflow import AirflowException


def start(**kwargs):
    return "Hello World"


def fail(**context):
    raise AirflowException("Oh no a failure!") # Fail here

default_args = {
    'owner': 'Osmar',
    'depends_on_past': False,
    'start_date': datetime(2019, 7, 1),
    'email': ['ocoronel@sentry.io'],
    'email_on_failure': False,
    'email_on_retry': False,
    'retries': 1,
    'retry_delay': timedelta(minutes=1),
}

dag = DAG('failed_dag', default_args=default_args, schedule_interval=timedelta(1))


t1 = PythonOperator(task_id="start", provide_context=True, python_callable=start, dag=dag)

t2 = \
    PythonOperator(task_id='fail',
                   provide_context=True,
                   python_callable=fail,
                   dag=dag)

t3 = BashOperator(task_id="middle", bash_command="true", dag=dag)
t4 = BashOperator(task_id="concurrent", bash_command="true", dag=dag)
t5 = BashOperator(task_id="other_start", bash_command="true", dag=dag)
t6 = BashOperator(task_id="irrelevant", bash_command="true", dag=dag)

t1 >> [t3, t4] >> t2
t5 >> t2
t1 >> t6
```
The end result would be,
![](https://uc60cb219178fdcd90eda3880401.previews.dropboxusercontent.com/p/thumb/AAe25_QEtxUbGRWDIykTlafoUC7Oq9RgFELQbO1zN1vjR-86BOrpn50n__tB1YUkHqKr_80hTuQEHdaWQmHXPT5QinSJnZWG8W08hvPxug-2DT_iYaQut_NcMz2BQxiftvBf5jxT-TK4cebeP909jby9EzYib6Ertbf8pT1sle1IrMcJAtEc2Me948BWwwOygO2-7G3LIZtdRDplBi38bJGD9gM142mqEB_4VSex3frrF99bDgoUBAWzQe-QVkWik0rzwf1YQeIKnY39PG9-w89VMxHWMquEt55aTGiPSjJ4Q2gHgBWvUM_hOQJrDOHMhvQa9BV9ZgFuXsNA7PmkF4rAiMc4xV3HzXAS1u32ZUBxlkc5WD--nNovH4--tJVL2yeD2G6RxC2y7rZtlq-OraWhG7krm9KRib7gbrX8VkSE4XCn_1DzWdvb_Dlr2ShI0oaBwGUDL9UyI5UsOX1goLBg/p.png?size=2048x1536&size_mode=3)
and in Sentry
![](https://uc9f467aa06761ed61386d108a3c.previews.dropboxusercontent.com/p/thumb/AAcPu4Na75aN-X-9yF-2UqzaVQ0wDjdrnIxwSMNCxEfh7IFqtfLpIWtPqs_-Vjug5I9blTt0l3VC6k-m_GXmkO-c89_8jhHyrGPeYxlEnsok3h-NkPjZn4TtVku5Ym6RfFCTlxZY91gQZgzdP825AKwuf19DEwvdpRzyXLep1cVTTgXyaObvZhET3kkcp6R1wmRApTwLrPHe7yXkwpPI1pQYY5Je5OGVWvNJP5w5aB0hRuLpLydc-KoXJgGRClbJy_f5Ydoc30g3ubvBRjuO-iGoqBTRJarf1l_fxjYM9N8d-sLsvIxQpX5FWt4TYXpZglDrx8trfX4G2SOGvXYWkx-dlH-C5Okg6Zxb9v6nKoayzjABUE0LY2r12MIqGSxkL39vYpsZfjl20ywaZ9h5LkZZvRJQ5nyx8XXdoIk0rhiLrS7nk2zm7qplvfGrg3eQPdMkAN2jhK7YRbXK9VV3KpJv/p.png?fv_content=true&size_mode=5)

**Comment by psdon** [comment]
This example doesn't work anymore
