### ISSUE TITLE
Broken plugin: [/opt/airflow/plugins/sentry_plugin/__init__.py] protocol not found

### ISSUE THREAD

**Issue by aerasoft** [getsentry/sentry-airflow#9]
I seeing this error pop up after installation. Could you help me?
<img width="872" alt="Screenshot 2019-08-06 at 3 10 58 PM" src="https://user-images.githubusercontent.com/24838294/62552002-758a2300-b85c-11e9-8306-44ba04e37187.png">

**Comment by psdon** [comment]
how do you install it?

**Comment by aerasoft** [comment]
@psdon i just git clone into the airflow plugins folder

**Comment by psdon** [comment]
Looks like you haven't install the dependencies

**Comment by psdon** [comment]
#6

**Comment by mikeclarke** [comment]
The `protocol not found` exception looks like it might be related to https://github.com/eventlet/eventlet/issues/370. Is it possible that `/etc/protocols` is missing?

**Comment by aerasoft** [comment]
Pip freeze has all the requirements 

```
apache-airflow>=1.10.2
sentry-sdk>=0.5.4
celery>=4.3.0
blinker>=1.1
```
I manually installed them just to be sure as well. I am still seeing the error. Could @psdon

**Comment by mikeclarke** [comment]
@aerasoft Do you mind checking if that `/etc/protocols` file is on the file system, to see if that linked issue on eventlet is related?

**Comment by aerasoft** [comment]
@mikeclarke It doesn't exist in the docker container. Any guide on how to set this up?

**Comment by mikeclarke** [comment]
The StackOverflow post mentioned in the eventlet issue (https://stackoverflow.com/questions/40184788/protocol-not-found-socket-getprotobyname#answer-40185488) suggests re-installing the `netbase` package to make sure the file ends up on the filesystem, but that will depend on your specific docker image that you're using.

**Comment by mikeclarke** [comment]
Going to close this for now given it seems tied to those related issues in `eventlet`.
